name: Build and Upload RootFS

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run the Docker container
      - name: Run Docker container
        run: |
          docker run \
            --env PS1="ADC(\#)[\d \T:\w]\\$ " \
            --interactive \
            --privileged \
            --rm \
            --volume "$PWD/rootfs:/rootfs" \
            "index.docker.io/library/archlinux:latest" \
            /bin/bash -c "pacman -Sy arch-install-scripts --noconfirm && mkdir -p /rootfs && pacstrap -K /rootfs base linux && echo 'Rootfs created successfully'"

      - name: Create rootfs tarball
        run: |
          tar --numeric-owner \
            --xattrs \
            --acls \
            --exclude-from="$PWD/exclude" \
            -C "$PWD/rootfs" \
            -c . \
            -f "$PWD/zenithos-rootfs.tar"

      - name: Create rootfs tarball
        run: |
          zstd --long -T0 -8 "$PWD/zenithos-rootfs.tar" && sha256sum "zenithos-rootfs.tar.zst" > "zenithos-rootfs.tar.zst.SHA256"

      # Upload the artifact
      - name: Upload zst artifact
        uses: actions/upload-artifact@v4
        with:
          name: zenithos-rootfs.tar.zst
          path: zenithos-rootfs.tar.zst

      - name: Upload zst artifact checksum
        uses: actions/upload-artifact@v4
        with:
          name: zenithos-rootfs.tar.zst.SHA256
          path: zenithos-rootfs.tar.zst.SHA256
