name: Build and Upload Rootfs

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 0"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker container
        run: |
          docker run \
            --env PS1="ADC(\#)[\d \T:\w]\\$ " \
            --interactive \
            --privileged \
            --rm \
            --volume "$PWD/rootfs:/rootfs" \
            "index.docker.io/library/archlinux:latest" \
            /bin/bash -c "pacman -Sy arch-install-scripts --noconfirm && mkdir -p /rootfs && \
              pacstrap -K /rootfs base base-devel linux-zen linux-firmware linux-zen-headers \
              ukify btrfs-progs intel-ucode amd-ucode podman toolbox networkmanager \
              nano git vim openssh zsh acpid sudo mandb man-pages bluez bluez-utils \
              pipewire alsa-utils pipewire-pulse firefox plasma && \
              echo 'Rootfs created successfully'"

      - name: Copy exclude file
        run: |
          mkdir -p src && cp exclude ./src

      - name: Create rootfs tarball
        run: |
          docker run \
              --env PS1="ADC(\#)[\d \T:\w]\\$ " \
              --interactive \
              --privileged \
              --rm \
              --volume "$PWD/rootfs:/rootfs" \
              --volume "$PWD/src:/src" \
              --volume "$PWD/build:/build" \
              "index.docker.io/library/archlinux:latest" \
              /bin/bash -c "tar --numeric-owner --xattrs --acls --exclude-from=/src/exclude -C /rootfs -c . -f /build/zenithos-rootfs.tar"

      - name: Create zst Archive
        run: |
          docker run \
              --env PS1="ADC(\#)[\d \T:\w]\\$ " \
              --interactive \
              --privileged \
              --rm \
              --volume "$PWD/build:/build" \
              "index.docker.io/library/archlinux:latest" \
              /bin/bash -c "zstd --long -T0 -8 /build/zenithos-rootfs.tar ; sha256sum ./build/zenithos-rootfs.tar.zst > ./build/zenithos-rootfs.tar.zst.SHA256"

      - name: Upload zst artifact
        uses: actions/upload-artifact@v4
        with:
          name: zenithos-rootfs.tar.zst
          path: ./build/zenithos-rootfs.tar.zst

      - name: Upload zst artifact checksum
        uses: actions/upload-artifact@v4
        with:
          name: zenithos-rootfs.tar.zst.SHA256
          path: ./build/zenithos-rootfs.tar.zst.SHA256
