name: Build and Push Container Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo "${{ env.REGISTRY_PASSWORD }}" | podman login ghcr.io -u "${{ env.REGISTRY_USER }}" --password-stdin

      - name: Build container image
        run: |
          TAG="$(date +%Y%m%d%H%M%S)"
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/zenith-os:$TAG"
          podman build -t "$IMAGE_NAME" -f Containerfile .
          echo "Built image: $IMAGE_NAME"

      - name: Push container image
        run: |
          TAG="$(date +%Y%m%d%H%M%S)"
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/zenith-os:$TAG"
          podman push "$IMAGE_NAME"
          echo "Pushed image: $IMAGE_NAME"